### PR TITLE
SOR-1294: Filter out imps with no size

### PR DESCRIPTION
**Pull request by shannonAB**
Check that bid.sizes has at least one element. Add a test for this.

### CODE REVIEW

**Comment by shannonAB** [comment]
Ugh I don't know why it's including the previous 4 commits.

**Comment by edmonl** [comment]
Usually because it was not branched off of master

**Comment by shannonAB** [comment]
It was branched off of `origin/sortable_master`, was that wrong?

**Comment by shannonAB** [comment]
Ohhhh. Will try again with a new PR then

**Pull request closed without merging**
